version: "3.1"
services:
  db:
    image: mariadb
    container_name: coworking_mariadb
    ports:
      - 3306:3306
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: bbw123

    volumes:
      - /home/jelena/database:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: coworking_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    restart: always
    ports:
      - 80:80
    volumes:
      - /sessions
    links:
      - db